name: Build and upload to PyPI

on:
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build sdist
        run: pipx run build --sdist

      - name: Test sdist
        run: |
          python -m pip install dist/thorvg_python-*.tar.gz
          pip install Pillow pytest
          pytest

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 7

  build_wheels:
    name: Build wheels on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            arch: x86_64
            plat: win_amd64
          - os: windows-latest
            arch: x86
            plat: win32
          - os: windows-latest
            arch: armv8
            plat: win_arm64
          - os: macos-15-intel
            arch: x86_64
            plat: macosx_10_9_x86_64
          - os: macos-15
            arch: universal2
            plat: macosx_10_9_universal2
          - os: macos-15
            arch: armv8
            plat: macosx_11_0_arm64
          - os: ubuntu-latest
            arch: x86_64
            plat: x86_64
          - os: ubuntu-latest
            arch: i686
            plat: i386
          - os: ubuntu-24.04-arm
            arch: aarch64
            plat: aarch64
          - os: ubuntu-latest
            arch: ppc64le
            plat: ppc64le
          - os: ubuntu-latest
            arch: s390x
            plat: s390x

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        if: runner.os != 'Linux'
        env:
          TVGPY_COMPILE_TARGET: ${{matrix.arch}}
        run: |
          pip install build wheel
          python -m build --wheel --outdir wheelhouse
          python -m wheel tags --platform-tag ${{matrix.plat}} ./wheelhouse/*.whl
          rm ./wheelhouse/*-none-any.whl
        shell: bash
      
      - name: Test wheels
        if: matrix.plat != 'win32' && matrix.plat != 'win_arm64' && runner.os != 'Linux'
        run: |
          pip install ./wheelhouse/*.whl Pillow pytest
          pytest
        shell: bash

      - name: Build and test wheels (Linux)
        if: runner.os == 'Linux'
        run: |
          docker run \
          --rm \
          -v $(pwd):/${GITHUB_WORKSPACE} \
          -w ${GITHUB_WORKSPACE} \
          --platform linux/${{matrix.plat}} \
          quay.io/pypa/manylinux2014_${{matrix.arch}} \
          /bin/bash -c \
          'scl enable devtoolset-10 "
          python3.12 -m build --wheel --outdir wheelhouse_anytag &&
          python3.12 -m pip install --root-user-action=ignore auditwheel &&
          auditwheel repair -w wheelhouse --plat manylinux2014_${{matrix.arch}} ./wheelhouse_anytag/*.whl" &&
          python3.12 -m pip install --root-user-action=ignore ./wheelhouse/*.whl pytest &&
          python3.12 -m pip install --only-binary ":all:" --root-user-action=ignore Pillow; true &&
          python3.12 -m pytest
          '

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
          retention-days: 7

  # upload_pypi_test:
  #   needs: [build_wheels, build_sdist]
  #   runs-on: ubuntu-latest
  #   # upload to PyPI on every tag starting with 'v'
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
  #   steps:
  #     - name: "Download artifacts"
  #       uses: actions/download-artifact@v4
      
  #     - name: "Move packages to the dist/ folder"
  #       run: |
  #         mkdir dist/
  #         mv sdist/* dist/
  #         mv wheels-*/*.whl dist/

  #     - name: "Publish packages on PyPI"
  #       uses: pypa/gh-action-pypi-publish@v1.5.0
  #       with:
  #         password: ${{ secrets.PYPI_API_TOKEN }}
  #         repository_url: https://test.pypi.org/legacy/

  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: "Download artifacts"
        uses: actions/download-artifact@v4
      
      - name: "Move packages to the dist/ folder"
        run: |
          mkdir dist/
          mv sdist/* dist/
          mv wheels-*/*.whl dist/

      - name: "Publish packages on PyPI"
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}